### ISSUE TITLE
How can I download the crtomo inversion code?

### ISSUE THREAD

**Issue by xichaoqiang** [geophysics-ubonn/crtomo_tools#3]
Hello, Thanks For sharing this package.
How can I download the crtomo inversion code?

**Comment by m-weigand** [comment]
Hi there,
although the Python wrapper for CRTomo is open source, unfortunately the inversion code itself is not.
If you are interested in using it you could try to contact Prof. Kemna and ask for the code/a binary

https://www.geo.uni-bonn.de/people/prof.-dr.-andreas-kemna

I'm closing this issue as I cannot do more here for you, but feel free to open another issue if you think I can help more.
