### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ZSSSSZJU** [geophysics-ubonn/crtomo_tools#4]
Thank you very much for sharing this package, but I would like to know how to use this package. Obviously, there are not enough instructions to guide me to operate inversion

**Comment by m-weigand** [comment]
I'm closing this issue due to it's age. Please reopen if you are still interested in doing inversions with Crtomo.

**Comment by ZSSSSZJU** [comment]
Hello Professor Weigand ! 
  Receiving your reply makes me so happy ! CRTomo has been widely and successfully applied to the field research of IP method since it was developed by Professor Kemna. I am excited to find that many descriptive files have been uploaded to Github ( https://geophysics-ubonn.github.io/crtomo_tools/), ) recently. Does this mean that CRTomo is already open source ? I 'm so excited because I 've always been very interested in using CRTomo for IP ( SIP ) inversion ! 
Looking forward to your reply !
