### ISSUE TITLE
Questions about whether CRTomo is already open source

### ISSUE THREAD

**Issue by ZSSSSZJU** [geophysics-ubonn/crtomo_tools#5]
Hello Professor Weigand !
 I am the questioner of issue 4 (https://github.com/geophysics-ubonn/crtomo_tools/issues/4). Receiving your reply makes me so happy ! 
CRTomo has been widely and successfully applied to the field research of IP method since it was developed by Professor Kemna. I am excited to find that many descriptive files have been uploaded to Github ( https://geophysics-ubonn.github.io/crtomo_tools/), recently. Does this mean that CRTomo is already open source ? I 'm so excited because I 've always been very interested in using CRTomo for IP ( SIP ) inversion！
Looking forward to your reply !

**Comment by m-weigand** [comment]
Yes, CRTomo is open source. However, please keep in mind that we have only limited resources for external user support. In general, unless you have very specific use cases, we recommend to use pyGimli (https://www.pygimli.org/). This project is much larger and has a much larger community that can help.

While you have been warned, our software stack at the moment is comprised of three main components:

* CRTomo itself: the Fortran code for complex-resistivity forward and inverse modelling:
   https://github.com/geophysics-ubonn/crtomo_stable
   
 * crtomo-tools: The Python wrapper and helper libraries. These are the tools that we recommend to interface CRTomo with:
   * code: https://github.com/geophysics-ubonn/crtomo_tools
   * Documentation: https://geophysics-ubonn.github.io/crtomo_tools/index.html
 * REDA: Our library for raw data import and visualization:
   * code: https://github.com/geophysics-ubonn/crtomo_tools
   * Documentation: https://geophysics-ubonn.github.io/reda/
   
   If you are using linux on an amd64 system, you may be lucky and the pre-compiled binaries work. In that case you can just install them using pip with:
    ```
    pip install crtomo-bin-wrapper
    ```
    
    The other libraries can be installed in a similar manner:
    ```
    pip install reda crtomo-tools
    ```
    
    Start by looking at the examples in the documentation above. While we appreciate any bug reports, keep in mind that internal issues have priority. 
    And again, please check out pygimli and use that, if applicable to your application.
